# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x05proto\"^\n\x07Message\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x14\n\x0cobfReference\x18\x03 \x01(\t\x12\x10\n\x08methodId\x18\x04 \x01(\t\x12\x11\n\targuments\x18\x05 \x01(\x0c\"c\n\x05\x43omic\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0c\n\x04\x61uth\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x11\n\tcondition\x18\x05 \x01(\x05\x12\x0e\n\x06status\x18\x06 \x01(\x05\"\x15\n\x07\x43omicId\x12\n\n\x02id\x18\x01 \x01(\x05\"9\n\tComicList\x12\x1c\n\x06\x63omics\x18\x01 \x03(\x0b\x32\x0c.proto.Comic\x12\x0e\n\x06\x66ilter\x18\x02 \x01(\x05\"K\n\x08Response\x12\n\n\x02id\x18\x01 \x01(\x05\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.proto.ResponseStatus\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\x14\n\x05\x45rror\x12\x0b\n\x03\x65rr\x18\x01 \x01(\t*5\n\x0eResponseStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x0b\n\x07TIMEOUT\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSESTATUS']._serialized_start=403
  _globals['_RESPONSESTATUS']._serialized_end=456
  _globals['_MESSAGE']._serialized_start=25
  _globals['_MESSAGE']._serialized_end=119
  _globals['_COMIC']._serialized_start=121
  _globals['_COMIC']._serialized_end=220
  _globals['_COMICID']._serialized_start=222
  _globals['_COMICID']._serialized_end=243
  _globals['_COMICLIST']._serialized_start=245
  _globals['_COMICLIST']._serialized_end=302
  _globals['_RESPONSE']._serialized_start=304
  _globals['_RESPONSE']._serialized_end=379
  _globals['_ERROR']._serialized_start=381
  _globals['_ERROR']._serialized_end=401
# @@protoc_insertion_point(module_scope)
